development:
 host: ds029807.mongolab.com
 port: 29807
 username: railsbay
 password: railsbay123
 database: railsbay

test:
 host: localhost
 database: meetlinkshare_api_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>
 # slaves:
 #   - host: slave1.local
 #     port: 27018
 #   - host: slave2.local
 #     port: 27019