development:
 host: ds029807.mongolab.com
 port: 29807
 username: railsmine
 password: railsmine123
 database: railsmine

test:
 host: localhost
 database: meetlinkshare_api_test

# set these environment variables on your prod server
production:
 host: ds029807.mongolab.com
 port: 29807
 username: railsmine
 password: railsmine123
 database: railsmine
 # slaves:
 #   - host: slave1.local
 #     port: 27018
 #   - host: slave2.local
 #     port: 27019
